### ISSUE TITLE
how to set the -p task.cpus in parameters 

### ISSUE THREAD

**Issue by shangguandong1996** [canceromics/MeRIPseqPipe#10]
Hi, Dear developer
I want to set the threads or cpus in parameters because I find it seems MeRIPseqPipe will just use one cpus for each jobs. I have seen many jobs use `task.cpus`

```
$ grep task.cpus main.nf 
        hisat2-build -p ${task.cpus} -f $fasta --exon Hisat2Index/${fasta.baseName}.exon --ss Hisat2Index/${fasta.baseName}.ss Hisat2Index/${fasta.baseName}
        STAR --runThreadN ${task.cpus} \
    hisat2-build -p ${task.cpus} -f $rRNA_fasta rRNAindex/${rRNA_fasta.baseName}
            fastp -i ${reads} -o ${add_aligners} -j ${sample_name}_fastp.json -h ${sample_name}_fastp.html -w ${task.cpus}
            fastp -i ${reads[0]} -o ${add_aligners_1} -I ${reads[1]} -O ${add_aligners_2} -j ${sample_name}_fastp.json -h ${sample_name}_fastp.html -w ${task.cpus}
            -p ${task.cpus} --dta --un-gz ${sample_id}.fastq.gz \
            samtools view -@ ${task.cpus} -Shub - | \
            samtools sort -@ ${task.cpus} -o ${sample_name}_rRNA_sort.bam -
            -p ${task.cpus} --dta --un-conc-gz ${sample_name}_fastq.gz \
            samtools view -@ ${task.cpus} -Shub - | \
            samtools sort -@ ${task.cpus} -o ${sample_name}_rRNA_sort.bam -
        tophat  -p ${task.cpus} \

```

I have read the [documents](https://github.com/canceromics/MeRIPseqPipe/blob/main/docs/parameter_docs.md), but it seems that it do not mention that how to set the `task.cpus` for each jobs. 
So I am wondering whehther you can help me.

Please forgive me if I misunderstand something :)

Best wishes

Guandong Shang

**Comment by canceromics** [comment]
Hi! If you want to change the CPU number of certain processes, you can edit tha main.nf file, modify the code like:
`process big_job {
  **cpus 8**
  executor 'sge'

  """
  blastp -query input_sequence -num_threads ${task.cpus}
  """
}`
