### ISSUE TITLE
Operator into has been deprecated -- it's not available in DSL2 syntax 

### ISSUE THREAD

**Issue by matarina** [canceromics/MeRIPseqPipe#11]
Check script 'MeRIPseqPipe/main.nf' at line: 189 ：

compareLines.into{
compareLines_for_DESeq2; compareLines_for_edgeR; compareLines_for_plot;
compareLines_for_diffm6A; compareLines_for_arranged_result
}

any way to resolve this error?

**Comment by canceromics** [comment]
Hi! You can use a lower version of nextflow (< 22.03.0-edge) or you can restore the previous behavior setting in into your environment the following variable:
`export NXF_DEFAULT_DSL=1`
