### ISSUE TITLE
/bin/bash: .command.run: No such file or directory

### ISSUE THREAD

**Issue by wangyanmin123** [canceromics/MeRIPseqPipe#12]
I have downloaded the installation package and singularity (export NXF_SINGULARITY_CACHEDIR=/home/zhangli_lab/wangyanmin/scratch60/meripseqpipe/2) image separately, the path is /home/zhangli_lab/wangyanmin/scratch60/meripseqpipe/2 Software: nextflow, singularity has been installed , testing nextflow run path/to/meripseqpipe -profile test,singularity has a problem, I don't know if it is my running problem or the configuration file needs to be modified, I hope I can get help, thank you very much

Here is my run command and output error:
[wangyanmin@login01 2]$  nextflow MeRIPseqPipe/main.nf -c MeRIPseqPipe/nextflow.config -profile test,singularity 
N E X T F L O W  ~  version 21.04.0
Launching `MeRIPseqPipe/main.nf` [magical_babbage] - revision: 992c8903be
WARN: There's no process matching config selector: fastp -- Did you mean: Fastp?
WARN: There's no process matching config selector: sort
============You are running MeRIPseqPipe with the following parameters===============
Checking parameters ...
===================================Pipeline summary=============================
Max Resources                  : 6 GB memory, 2 cpus, 2d time per job
Container                       : singularity - kingzhuky/meripseqpipe:dev
Output dir                     : /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2/MeRIPseqPipe/results
Launch dir                     : /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2
Working dir                    : /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2/work
Script dir                     : /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2/MeRIPseqPipe
User                           : wangyanmin
Config Profile                 : test,singularity
Config Description              : Minimal test dataset to check pipeline function
=====================================Reads types================================
SingleEnd                      : Single-End
Stranded                       : no
gzip                           : true
====================================Mode selected==============================
aligners                       : star
peakCalling_mode               : independence
peakMerged_mode                : rank
expression_analysis_mode       : DESeq2
methylation_analysis_mode      : QNB
==================================Input files selected==========================
Reads Path                     : false
fasta file                     : /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2/MeRIPseqPipe/test_datasets/reference/TEST.fa
Gtf file                       : /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2/MeRIPseqPipe/test_datasets/reference/TEST.gtf
Design file                    : /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2/MeRIPseqPipe/test_datasets/inputfiles/designfile_single.tsv
Compare file                   : /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2/MeRIPseqPipe/test_datasets/inputfiles/comparefile.txt
==================================Skip model selected==========================
Skip samtools sort             : false
Skip expression analysis       : false
Skip peakCalling               : false
Skip diffpeakCalling           : false
Skip annotation                : false
Skip qc                        : false
executor >  local (10)
[b1/660778] process > CheckDesignCompare         [  0%] 0 of 1
[01/6779e5] process > makeBED12 (gtf2bed12)      [  0%] 0 of 1
[bc/441837] process > makechromesize (gtf2bed12) [  0%] 0 of 1
[-        ] process > MakeTophat2Index           -
[-        ] process > MakeHisat2Index            -
[-        ] process > MakeBWAIndex               -
[a0/dd4b7e] process > MakeStarIndex (star_index) [  0%] 0 of 1
[-        ] process > MakerRNAindex              -
[cb/25c8fb] process > Fastp (control_1.input)    [  0%] 0 of 8
executor >  local (10)
[b1/660778] process > CheckDesignCompare         [  0%] 0 of 1
[01/6779e5] process > makeBED12 (gtf2bed12)      [  0%] 0 of 1
[bc/441837] process > makechromesize (gtf2bed12) [  0%] 0 of 1
[-        ] process > MakeTophat2Index           -
[-        ] process > MakeHisat2Index            -
[-        ] process > MakeBWAIndex               -
[a0/dd4b7e] process > MakeStarIndex (star_index) [  0%] 0 of 1
[-        ] process > MakerRNAindex              -
[cb/25c8fb] process > Fastp (control_1.input)    [  0%] 0 of 8
executor >  local (11)
[b1/660778] process > CheckDesignCompare         [  0%] 0 of 1
[01/6779e5] process > makeBED12 (gtf2bed12)      [  0%] 0 of 1
[bc/441837] process > makechromesize (gtf2bed12) [  0%] 0 of 1
[-        ] process > MakeTophat2Index           -
[-        ] process > MakeHisat2Index            -
[-        ] process > MakeBWAIndex               -
[a0/dd4b7e] process > MakeStarIndex (star_index) [  0%] 0 of 1
[-        ] process > MakerRNAindex              -
[69/b5fa1d] process > Fastp (control_1.ip)       [  0%] 0 of 8
[-        ] process > Fastqc                     -
[-        ] process > Tophat2Align               -
[-        ] process > Hisat2Align                -
[-        ] process > BWAAlign                   -
[-        ] process > StarAlign                  -
[-        ] process > SortRename                 -
[-        ] process > RSeQC                      -
[-        ] process > CreateBedgraph             -
[-        ] process > multiqc                    -
[-        ] process > FeatureCount               -
[-        ] process > DESeq2                     -
[-        ] process > EdgeR                      -
[-        ] process > Metpeak                    -
[-        ] process > Macs2                      -
[-        ] process > MATKpeakCalling            -
[-        ] process > MeyerPrepration            -
[-        ] process > Meyer                      -
[-        ] process > PeakMerge                  -
[-        ] process > BedAnnotated               -
[-        ] process > MotifSearching             -
[-        ] process > PeaksMotifReport           -
[-        ] process > PeaksQuantification        -
[-        ] process > diffm6APeak                -
[-        ] process > SingleNucleotidePrediction -
[-        ] process > DiffReport                 -
[-        ] process > CreateIGVjs                -
[-        ] process > get_software_versions      [  0%] 0 of 1
executor >  local (11)
[b1/660778] process > CheckDesignCompare         [100%] 1 of 1, failed: 1 ✘
[01/6779e5] process > makeBED12 (gtf2bed12)      [100%] 1 of 1, failed: 1 ✘
[bc/441837] process > makechromesize (gtf2bed12) [100%] 1 of 1, failed: 1 ✘
[-        ] process > MakeTophat2Index           -
[-        ] process > MakeHisat2Index            -
[-        ] process > MakeBWAIndex               -
[a0/dd4b7e] process > MakeStarIndex (star_index) [100%] 1 of 1, failed: 1 ✘
[-        ] process > MakerRNAindex              -
[69/b5fa1d] process > Fastp (control_1.ip)       [ 88%] 7 of 8, failed: 7[-        ] process > Fastqc                     -
[-        ] process > Tophat2Align               -
[-        ] process > Hisat2Align                -
[-        ] process > BWAAlign                   -
[-        ] process > StarAlign                  -
[-        ] process > SortRename                 -
[-        ] process > RSeQC                      -
[-        ] process > CreateBedgraph             -
[-        ] process > multiqc                    -
[-        ] process > FeatureCount               -
[-        ] process > DESeq2                     -
[-        ] process > EdgeR                      -
[-        ] process > Metpeak                    -
[-        ] process > Macs2                      -
[-        ] process > MATKpeakCalling            -
[-        ] process > MeyerPrepration            -
[-        ] process > Meyer                      -
[-        ] process > PeakMerge                  -
[-        ] process > BedAnnotated               -
[-        ] process > MotifSearching             -
[-        ] process > PeaksMotifReport           -
[-        ] process > PeaksQuantification        -
[-        ] process > diffm6APeak                -
[-        ] process > SingleNucleotidePrediction -
[-        ] process > DiffReport                 -
[-        ] process > CreateIGVjs                -
[-        ] process > get_software_versions      [  0%] 0 of 1
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'MakeStarIndex (star_index)'

executor >  local (11)
[b1/660778] process > CheckDesignCompare         [100%] 1 of 1, failed: 1 ✘
[01/6779e5] process > makeBED12 (gtf2bed12)      [100%] 1 of 1, failed: 1 ✘
[bc/441837] process > makechromesize (gtf2bed12) [100%] 1 of 1, failed: 1 ✘
[-        ] process > MakeTophat2Index           -
[-        ] process > MakeHisat2Index            -
[-        ] process > MakeBWAIndex               -
[a0/dd4b7e] process > MakeStarIndex (star_index) [100%] 1 of 1, failed: 1 ✘[-        ] process > MakerRNAindex              -
[69/b5fa1d] process > Fastp (control_1.ip)       [ 88%] 7 of 8, failed: 7
[-        ] process > Fastqc                     -
[-        ] process > Tophat2Align               -
[-        ] process > Hisat2Align                -
[-        ] process > BWAAlign                   -
[-        ] process > StarAlign                  -
[-        ] process > SortRename                 -
[-        ] process > RSeQC                      -
[-        ] process > CreateBedgraph             -
[-        ] process > multiqc                    -
[-        ] process > FeatureCount               -
[-        ] process > DESeq2                     -
[-        ] process > EdgeR                      -
[-        ] process > Metpeak                    -
[-        ] process > Macs2                      -
[-        ] process > MATKpeakCalling            -
[-        ] process > MeyerPrepration            -
[-        ] process > Meyer                      -
[-        ] process > PeakMerge                  -
[-        ] process > BedAnnotated               -
[-        ] process > MotifSearching             -
[-        ] process > PeaksMotifReport           -
[-        ] process > PeaksQuantification        -
[-        ] process > diffm6APeak                -
[-        ] process > SingleNucleotidePrediction -
[-        ] process > DiffReport                 -
[-        ] process > CreateIGVjs                -
[-        ] process > get_software_versions      [  0%] 0 of 1
Error executing process > 'MakeStarIndex (star_index)'

Caused by:
  Process `MakeStarIndex (star_index)` terminated with an error exit status (127)

Command executed:

  mkdir StarIndex
  STAR --runThreadN 2         --runMode genomeGenerate         --genomeDir StarIndex         --genomeFastaFiles TEST.fa         --sjdbGTFfile TES
T.gtf         --sjdbOverhang 49 	--limitGenomeGenerateRAM 36000000000
Command exit status:
  127

Command output:
  (empty)

Command error:
  /bin/bash: line 0: cd: /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2/work/a0/dd4b7e53ea2615b9da7b88c2684c2d: No such file or directory
  /bin/bash: .command.run: No such file or directory

Work dir:
  /GPFS/zhangli_lab_temp/wangyanmin/meripseqpipe/2/work/a0/dd4b7e53ea2615b9da7b88c2684c2d

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by canceromics** [comment]
Hi! You can edit the "nextflow.config" file and add config for singularity:
`  singularity {
     singularity.enabled = true
     singularity.runOptions = "-B /GPFS:/GPFS,/usr/local:/usr/local"
     params.matk_jar = "/MATK-1.0.jar"
  }`

**Comment by wangyanmin123** [comment]
> Hi! You can edit the "nextflow.config" file and add config for singularity: ` singularity { singularity.enabled = true singularity.runOptions = "-B /GPFS:/GPFS,/usr/local:/usr/local" params.matk_jar = "/MATK-1.0.jar" }`

Thank you very much for your help, I have successfully run
