### ISSUE TITLE
Remaining mentions of nf-core

### ISSUE THREAD

**Issue by ewels** [canceromics/MeRIPseqPipe#3]
Hi there,

Great work on what looks like a really nice pipeline! I notice that it looks like you used the @nf-core template to start the pipeline. This is no problem at all (we try to build our tools in such a way that people can do exactly this), but it looks like there are a few spots where you still need to strip out the default `nf-core/` prefixes: https://github.com/canceromics/MeRIPseqPipe/search?q=nf-core

https://github.com/canceromics/MeRIPseqPipe/blob/15e8ae21b6978f51cfe16a0f9042549369d1ed88/assets/email_template.html#L9

https://github.com/canceromics/MeRIPseqPipe/blob/15e8ae21b6978f51cfe16a0f9042549369d1ed88/assets/email_template.txt#L7

https://github.com/canceromics/MeRIPseqPipe/blob/15e8ae21b6978f51cfe16a0f9042549369d1ed88/assets/email_template.txt#L13

https://github.com/canceromics/MeRIPseqPipe/blob/15e8ae21b6978f51cfe16a0f9042549369d1ed88/bin/scrape_software_versions.py#L8

https://github.com/canceromics/MeRIPseqPipe/blob/15e8ae21b6978f51cfe16a0f9042549369d1ed88/assets/multiqc_config.yaml#L2

https://github.com/canceromics/MeRIPseqPipe/blob/b3f70b4c6cd80b410abb457b81fd5d2fc24c5dec/README.md#L5

It's always nice to have some mention of nf-core in the readme too, just to acknowledge the work that goes into the template. But it's not a requirement, at the end of the day we are happy if what we build is useful for others.

Thanks,

Phil

**Comment by likelet** [comment]
Hi Phil, I was just added as one of the maintainers of this project. I have been following nf-core for a long time.  Many thanks for your suggestion, and we did benefit a lot from nf-core project. I appreciated your advices, and we will keep using nf-core in our coming project. @ewels  
Also thanks for @apeltzer for my other project.

**Comment by ewels** [comment]
Great stuff! I just remembered that we have a fairly new tutorial listing which bits should be edited if using the template outside of @nf-core which might be helpful: https://nf-co.re/developers/tutorials/unofficial_pipelines

**Comment by likelet** [comment]
We will update the pipe by the tutorial .  @canceromics

**Comment by ewels** [comment]
Great stuff, thanks! One left! 😁 

https://github.com/canceromics/MeRIPseqPipe/blob/48808328bed689a5a3406783c226a8dc8dec84b1/assets/email_template.txt#L7-L13

**Comment by likelet** [comment]
Many thanks! @ewels
