### ISSUE TITLE
running MeRIPseqPipe (macs2 or other tools) without input/control datasets

### ISSUE THREAD

**Issue by PengNi** [canceromics/MeRIPseqPipe#6]
Hi developers,

Great pipeline! 

I want to use MeRIPseqPipe to process some of my own data, but I am new to MeRIP sequencing. I have a question now that is it possible to run this pipeline with only ip datasets (no input datasets)? I have read the [MACS protocol](https://www.nature.com/articles/nprot.2012.101), and it is said that MACS can run with only ip datasets. 

Thank you in advance!
Peng

**Comment by juneb4869** [comment]
Hi, Peng!  I'm sorry MeRIPseqPipe can not take only ip datasets as input in this version. Different from ChIP-seq, we recommend using the paired input and ip data when analyzing MeRIP-seq data to get more accurate results.

**Comment by PengNi** [comment]
@juneb4869 , thanks very much for your quick reply! Much appreciated! 
Since I don't have paired input datasets for my own ip datasets, do you think it is ok that I use RNA-seq data of the same sample as input dataset? Or the RNA-seq data of the same sample is actually the input control? I am very new to this area, I now don't know what the inpu control is used for. I checked the following figure, from what I understand, the input control will sequence all reads just as a normal RNA-seq?
![image](https://user-images.githubusercontent.com/4242364/172523446-621a495c-749b-49ae-aa8c-1cde79ebc97a.png)

**Comment by juneb4869** [comment]
Hi, Peng! The RNA-seq data of the same sample is actually the input control, you can take this as input data.

**Comment by PengNi** [comment]
@juneb4869 Thank you again!
