### ISSUE TITLE
Is picard/MarkDuplicates necessary before running peak calling?

### ISSUE THREAD

**Issue by PengNi** [canceromics/MeRIPseqPipe#7]
Hi @juneb4869 ,

Sorry to bother you again. I have successfully run MeRIPseqPipe on my own data. Now I have a question about **dpulicate reads after alignment**. In my data, I have ~20-47% duplicate reads for each sample accorrding to MultiQC report (see the following image). So I am wondering does this effect the peak calling results significantly? Do I need maybe run Picard before peak calling, just as the [nf-core rnaseq pipeline](https://github.com/nf-core/rnaseq)?
![image](https://user-images.githubusercontent.com/4242364/172817970-eb47a643-dcd7-4bc5-873d-7eb1a8165075.png)

Best,
Peng

**Comment by likelet** [comment]
According to my experience, remove duplicates is necessary for peak calling. Alternatively,  you may have a check the result by either removal or retain duplicates reads.

**Comment by PengNi** [comment]
@likelet , Thanks very much. I'll try and compare the results of running with and without UMI-tools/picard.
