### ISSUE TITLE
What is corresponding file to the Volcano Plot

### ISSUE THREAD

**Issue by mick42-star** [canceromics/MeRIPseqPipe#8]
Dear developer, 

I got this Volcano Plot of Different Methylation. I wonder what is the file corresponding to the volcano plot. I have checked the  m6AAnalysis/diffm6A/edgeR_diffm6A_A_Y.txt, but the numbers don't match with the numbers in the plot.

![image](https://user-images.githubusercontent.com/45997340/175865585-55aec29a-9586-41a0-a400-c3fceebded40.png)

**Comment by juneb4869** [comment]
Hi, mick42-star! The numbers in volcano plot shows the number of differentially methylated peaks in diffm6A result file with |log2FC| >= 0.58 and -log10(P value)  > -log10(0.05). And you can change the cutoff of log2FC with "dmlfc" parameter.

**Comment by mick42-star** [comment]
Hi juneb4869. Thanks for the reply. Another question, since the diffm6A show the FC for each m6A peak, I wonder whether it can calculate the m6A FC changes for corresponding genes.
