### ISSUE TITLE
MACS2 -g parameter

### ISSUE THREAD

**Issue by shangguandong1996** [canceromics/MeRIPseqPipe#9]
Hi, Dear developer.
I noticed the default paramter about MACS2 in MeRIPseqPipe is
<html>
<body>

MACS2 | 2.1.2 | default, -q 0.01 --keep-dup 5 -f BAM --nomodel
-- | -- | --

</body>
</html>

It seems that it use the default "-g hs " , which is 2.7e9. But how can I change the -g paramters for my species, which is more smaller than human?

**Comment by juneb4869** [comment]
Hi! For some individual needs, you can change the running code in the main.nf file.  As for this question, we calculated the genome size accoring to the reference genome user input.
```
macs2 callpeak -t *${peakcalling_tag}*ip*.bam -c *${peakcalling_tag}*input*.bam -g \$genome_size -n macs2_${peakcalling_tag} $arguments -f BAM --nomodel
    awk -v OFS="\\t" '{print \$1,\$2,\$3,\$1":"\$2"-"\$3,10^-\$8}' macs2_${peakcalling_tag}_peaks.narrowPeak > macs2_${peakcalling_tag}_normalized.bed
```

**Comment by shangguandong1996** [comment]
Thanks !
And thanks for your so convenient pipeline :)
